#!/usr/bin/env python3
import os, sys, signal
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
	sys.path.insert(0, _ROOT)
if not os.environ.get("SCC_SHARED") and os.path.isdir(os.path.join(_ROOT, "glade")):
	os.environ["SCC_SHARED"] = _ROOT

def sigint(*a):
	print("\n*break*")
	sys.exit(0)

if __name__ == "__main__":
	signal.signal(signal.SIGINT, sigint)

	import gi
	gi.require_version('Gtk', '3.0') 
	gi.require_version('GdkX11', '3.0') 
	gi.require_version('Rsvg', '2.0') 
	
	from scc.tools import init_logging
	from scc.paths import get_share_path
	init_logging()

	from gi.repository import Gtk, GObject
	glades = os.path.join(get_share_path(), "glade")
	images = os.path.join(get_share_path(), "images")
	if Gtk.IconTheme.get_default():
		Gtk.IconTheme.get_default().append_search_path(images)
### ### 	GObject.threads_init()
	
	from scc.gui.app import App
	App(glades, images).run(sys.argv)
