#!/usr/bin/env python3
"""
Script that integrates everything SCC can do in one executable.
Created so scc-* stuff doesn't polute /usr/bin.
"""
import os, sys
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
	sys.path.insert(0, _ROOT)
if not os.environ.get("SCC_SHARED") and os.path.isdir(os.path.join(_ROOT, "glade")):
	os.environ["SCC_SHARED"] = _ROOT

from scc.scripts import main

if __name__ == '__main__':
	main()
