#!/usr/bin/env python3
import os, sys
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
	sys.path.insert(0, _ROOT)
if not os.environ.get("SCC_SHARED") and os.path.isdir(os.path.join(_ROOT, "glade")):
	os.environ["SCC_SHARED"] = _ROOT

if __name__ == "__main__":
	from scc._launcher import osd_keyboard as _main
	_main()
